version: "3.9"

services:

  inventory:
    build: ./inventory
    container_name: inventory
    ports:
      - "8005:8000"
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis
      - REDIS_PORT=6379

  payment:
    build: ./payments
    container_name: payment
    ports:
      - "8001:8000"
    depends_on:
      - redis
      - inventory
    environment:
      - REDIS_URL=redis
      - REDIS_PORT=6379

  gateway:
    build: ./gateway
    ports:
      - "9000:8000"
    depends_on:
      - inventory
      - payment

  redis:
    image: redis:7
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    container_name: redis
    ports:
      - "6379:6379"

  payment_consumer:
    build: ./payments
    command: ["python", "consumer.py"]
    depends_on:
      - redis

  inventory_consumer:
    build: ./inventory
    command: ["python", "consumer.py"]
    depends_on:
      - redis
  
  auth_db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"

  auth:
      build: ./auth
      ports:
        - "8003:8000"
      depends_on:
        - auth_db
      env_file:
        - ./auth/.env